input_data:
  file1: "../data/raw/df_final_demo.txt"
  file3: "../data/raw/df_final_experiment_clients.txt"
  file2p1: "../data/raw/df_final_web_data_pt_1.txt"
  file2p2: "../data/raw/df_final_web_data_pt_2.txt"

output_data:
  file2: "../data/clean/digfootpring_groups_clean.csv"
  file1: "../data/clean/clean_final_demo.csv"
  file3: "../data/clean/cleaned_dataset.csv"
  file6: "../data/clean/df_compl_duration.csv"
  file7: "../data/clean/df_step_by_step.csv"
  file8: "../data/clean/funnel_all_groups.csv"
  file9: "../data/clean/funnel_variation.csv"
  file4: "../data/clean/error_compRate_clean.csv"
  file5: "../data/clean/error_compRate_tableau.csv"
